### ISSUE TITLE
DateTime::endOfDay, ::midnight, ::noon are resetting the TimeZone

### ISSUE THREAD

**Issue by g-stawarczyk** [aeon-php/calendar#23]
Using `DateTime::endOfDay`, `DateTime::midnight`, `DateTime::noon` causes resetting the TimeZone.

Example:
```
$dt = \Aeon\Calendar\Gregorian\DateTime::create(2020, 6, 20, 20, 0, 0, 0, 'Europe/Warsaw');
echo $dt;
```
In result we have: `2020-06-20T20:00:00+0200`

But in the result of
```
$dt = \Aeon\Calendar\Gregorian\DateTime::create(2020, 6, 20, 20, 0, 0, 0, 'Europe/Warsaw')->endOfDay();
echo $dt;
```
we have `2020-06-20T23:59:59+0000` and now the TimeZone is **UTC**

**Comment by norberttech** [comment]
Thanks you @g-stawarczyk ! 
This bug should be fixed by #25, sorry for late response, I can't get used to new github notifications, I guess it's time to get back into email notifications
