### ISSUE TITLE
Replacement for spaceship operator

### ISSUE THREAD

**Issue by christian-kolb** [aeon-php/calendar#293]
**Describe the feature**

With `\DateTimeImmutable` it's possible to use the spaceship operator `<=>` for sorting. As there is no operator overloading in PHP, it would be great to have an object oriented alternative to it for all components to prevent having to use helper functions.

**Expected behavior**

Have the following for sorting:

```php
$iterator->uasort(
    static fn (NewsEntry$a, NewsEntry $b) => $a->date->spaceshipOperator($b->date)
);
```

**Additional context**

The naming `spaceshipOperator` is the thing blocking me from working on a PR for it. I can't seem to find any examples for naming online. @norberttech Do you have an idea for the naming of it?

**Comment by norberttech** [comment]
Well, a spaceship is a comparison method so maybe something like `compareTo`? Not sure though if that's the best name, but definitely better than `spaceshipOperator` :P

**Comment by christian-kolb** [comment]
Yeah, although that's really not hard 😄
I did a little bit more research and found out that the comparator of the `intl` extension useses `compare`.

So I actually really like your proposal of `compareTo`. It has the same structure like `isEqualTo` and is aligned with other functions that do the same 🙂

If that works for you, I'd prepare a PR for it.

**Comment by norberttech** [comment]
sounds good to me!
