### ISSUE TITLE
`modify` is not 100% identical to the version from DateTimeImmutable

### ISSUE THREAD

**Issue by christian-kolb** [aeon-php/calendar#294]
**Describe the bug**

The following doesn't do anything, but should move the datetime to the next saturday of the internal timezone.

```
$nextSaturday = DateTime::fromString('2022-10-25 15:00:00')->modify('next Saturday');

echo $nextSaturday->format('Y-m-d');
```

should be `2022-10-27` but results in `2022-10-25`.

**Expected behavior**

`modify` should be identical to the implementation of `\DateTimeImmutable`.

**Additional context**

A possible solution would be to internally just call `self::fromDateTime($this->toDateTimeImmutable()->modify($modifier))` instead of a custom implementation.

But I don't know if there is a reason for not using a custom logic. Is there?

**Comment by norberttech** [comment]
[This is the reason](https://twitter.com/norbert_tech/status/1508698353898561541?s=20&t=J7JutG1WC3Zv75wzSq0HDQ) why using the default modify method did not work for me. 
I believe the fix is to check if in `$dateTimeParts` there is a `weekday`, calculate the delta and adjust the outcome.

**Comment by christian-kolb** [comment]
Yeah I also realized that there is an unintuitive logic within the `DateTimeImmutable`. Things like `2022-03-30` - 1 month is `2022-03-02` 🤦

**Comment by norberttech** [comment]
resolved by https://github.com/aeon-php/calendar/pull/304
