### ISSUE TITLE
Upgrading from 8.1.6 to 8.2

### ISSUE THREAD

**Issue by umpirsky** [aeon-php/calendar#356]
**Describe the bug**
In https://github.com/aeon-php/calendar/commit/ff7b809a817064a90ece9739006bff5597715781 composer requirements are changed:
```diff
- "php": "^7.4.2 || ~8.0 || ~8.1.10"
+ "php": "~8.1.10 || ~8.2"
```

Now it's hard to update from PHP `8.1.6` to `8.2` since `1.0.7` is compatible with `8.1.6` only, and `1.0.8` is compatible with `8.1.10+` only. 

In multi server environment, this makes upgrade harder.

**Expected behavior**
Is there a particular reason for this? Can we have a version that's compatible with both 8.1.6 and 8.2?

**Comment by norberttech** [comment]
hey @umpirsky ther reasony why only 8.1.10 is supported is related to this [bug](https://github.com/php/php-src/issues/9106)

**Comment by umpirsky** [comment]
I see, thanks.
